# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_post_accepted_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='accepted_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
